[package]
name = "demo-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
iced.workspace = true
iced-code-editor = { path = "../iced-code-editor" }
rfd = "0.16"

[lints]
workspace = true
