[package]
name = "demo-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
iced.workspace = true
iced-code-editor = { path = "../iced-code-editor" }
iced_aw = "0.13.0"
rfd = "0.17"

[lints]
workspace = true
